- packages/eslint-config-sentry-react/index.js
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/rules/jest.js
related to:
https://github.com/getsentry/sentry/pull/7787/
> add jest plugin

- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry/package.json
Preparing for babel 7 which will have us switching to eslint 5
> chore: Bump max eslint peer dep

- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry/package.json
- packages/eslint-config-sentry/rules/es6.js
Will bump a minor version and publish when merged and will then integrate into getsentry followed by sentry.
> feat: Enable prefer-const

- packages/eslint-config-sentry/rules/es6.js
> prefer-const should be an error

- package.json
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
- packages/eslint-config-sentry/package.json
> chore(upgrades): Upgrade eslint-plug-jest/react + update peer dep required version

- lerna.json
Commit message will now be
```
chore(release): Publish <version>
```
> chore(lerna): Add better default commit message for releases

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/strict.js
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-plugin-sentry/docs/rules/no-react-hooks.md
- packages/eslint-plugin-sentry/lib/rules/no-react-hooks.js
- packages/eslint-plugin-sentry/tests/lib/rules/no-react-hooks.js
Rule to disallow React Hooks as we discussed on our TSC.
> feat(rule): Adds rule to disallow React Hooks

- packages/eslint-config-sentry-app/index.js
- packages/eslint-plugin-sentry/docs/rules/no-digits-in-tn.md
- packages/eslint-plugin-sentry/lib/rules/no-digits-in-tn.js
- packages/eslint-plugin-sentry/tests/lib/rules/no-digits-in-tn.js
Relates to: https://github.com/getsentry/sentry/pull/16580
> feat(rule): Adds rule to disallow %d within tn()

- packages/eslint-config-sentry-app/package.json
Updated here: https://github.com/getsentry/sentry/pull/16505
> chore(deps): Bump peerDep for `prettier@1.19.1`

- CHANGELOG.md
- lerna.json
- packages/eslint-config-sentry-app/CHANGELOG.md
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-react/CHANGELOG.md
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry/CHANGELOG.md
- packages/eslint-config-sentry/package.json
> chore(release): Publish v1.31.0

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-react/rules/imports.js
**Description:** 
added a` import/order `rule that is common to all sentry packages:
> feat(rule): added common pathGroup

- packages/eslint-config-sentry/rules/base.js
See https://eslint.org/docs/rules/arrow-body-style
> feat(rule): Enable arrow-body-style

- .github/workflows/npmpublish.yml
- .github/workflows/test.yml
- lerna.json
- package.json
- packages/eslint-config-sentry-app/yarn.lock
This will auto publish to npm when we merge to master. This is just eslint configs so not sure we need to do anything fancy here.
> build(lerna): Fix yarn.lock not being updated when making new release

- .github/workflows/integration.yml
This adds an integration test for PRs (it will lint the relaxed ruleset against sentry repo).
> build(workflow): Add sentry integration test

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
This will auto-sort our imports
> feat(rules): Add `simple-import-sort` plugin and rule

- .github/workflows/integration.yml
- .github/workflows/npmpublish.yml
- .github/workflows/test.yml
- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-config-sentry-react/yarn.lock
This was throwing warnings since the upgrade to typescript@4.2
> feat(deps): Upgrade `@typescript-eslint/parser`

- packages/eslint-config-sentry/rules/base.js
See https://github.com/getsentry/sentry/pull/29764
> fix: curl rule was ill formed

- packages/eslint-config-sentry-react/index.js
too many false positives
docs
https://github.com/testing-library/eslint-plugin-testing-library/blob/a6d4cdaaf11cc4c9c2593cd6c72abacf3b15ad10/docs/rules/no-unnecessary-act.md
> fix: disable testing-library/no-unnecessary-act

- packages/eslint-config-sentry-react/rules/imports.js
> Revert "Actually diasslow all unnamed default exports"

- packages/eslint-config-sentry/rules/base.js
For this https://github.com/getsentry/sentry/pull/33365
> Add array-callback-return
