- packages/eslint-config-sentry-react/rules/jest.js
Disabled tests should error, if you want to keep them in, you must consciously disable the rule with inline comments. Otherwise it's too easy to commit disabled tests when you're just developing.
> rule(jest): error --> "jest/no-disabled-tests"

- packages/eslint-config-sentry-app/index.js
When we bump `babel-eslint` for babel 7 we will need this configuration via https://github.com/babel/babel-eslint/releases/tag/v9.0.0
> feat(babel7): Enable legacyDecorators for babel 7

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry/rules/base.js
We are reasonably inconsistent with our usage of braces. This can complicate refactoring as moving lines around can break behavior for if statements and if/else pairs. By always requiring braces we can avoid these issues and have clearer code.
If folks agree with this, I'll update sentry and getsentry to have more braces.
> RFC- feat(curly) Enable curly

- packages/eslint-config-sentry-react/rules/react.js
Don't allow `{'thing'}` as that expression doesn't require JSX braces.
> Add linting for redundant jsx literals.

- packages/eslint-config-sentry-app-strict/index.js
These rules are currently warnings in `eslint-config-sentry-app`, let's add them to the strict ruleset as errors so that we can try to catch these during pre commit hooks.
> feat(rule): Add current warnings as errors in strict ruleset

- packages/eslint-config-sentry/rules/base.js
When checking for unused vars/args, ignore them when they begin with an underscore (`_`).
Also allow unused positional args that occur before the last used argument.
> feat(rule): Change no-unused-vars to ignore underscores and unused positional args

- packages/eslint-config-sentry-app-strict/index.js
- packages/eslint-config-sentry/rules/base.js
Prefix with `_` to ignore
This is no autofixable and is difficult to manually update. Let's move the rule to the strict ruleset for now.
> feat(rule): Only check for unused args in strict ruleset

- packages/eslint-config-sentry/rules/base.js
We don't ever want to rely on type coercion for comparisons. Since this frequently comes up in code review, let's turn on the rule.
> Turn on eqeqeq rule

- lerna.json
- package.json
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/rules/react.js
- packages/eslint-config-sentry/package.json
- yarn.lock
I took the opportunity to upgrade dependencies too.
`eslint-config-prettier` went from v3.3.0 to v6.3.0 but the breaking changes does not affect us.
https://github.com/prettier/eslint-config-prettier/blob/master/CHANGELOG.md
> feat(react): Add rule to enforce usage of React.Fragment

- packages/eslint-config-sentry-app/rules/react.js
Seems to be breaking with the new fragment eslint rule since it was specified so old.
> ref(react): Configure to detect react version

- packages/eslint-config-sentry-react/rules/react.js
Cannot use `detect` because of `getsentry`
> fix(react): Fix react version settings

- packages/eslint-config-sentry-app/index.js
This will require developers to always import from `sentry-test/enzyme` instead of `enzyme`
> feat(rule): Add rule to restrict importing from `enzyme`

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
There was only 1 rule that we did not ever use, so removing this dependency
> feat(plugin): Remove `eslint-plugin-getsentry`

- packages/eslint-config-sentry-react/rules/react.js
Since this is a warning for `tsx` files because of some typescript compat, we should be consistent and downgrade this to a warning
> feat(rule): Downgrade `react/sort-comp` to a warning instead of error

- .github/workflows/npmpublish.yml
This changes GitHub actions to run `lerna publish` using the `from-package` option instead of `from-git`. This means that it will try to publish the version from package.json.
> build(actions): Change `lerna publish` to publish from package

- packages/eslint-config-sentry-app/strict.js
`grid-emotion` is deprecated and is blocking us from upgrading to
emotion@10. Add rule to strict ruleset so that if you touch a file using
it, you should be required to refactor it out.
> feat(rule): Restrict `grid-emotion` in strict ruleset

- CHANGELOG.md
- lerna.json
- packages/eslint-config-sentry-app/CHANGELOG.md
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/strict.js
- packages/eslint-config-sentry-react/CHANGELOG.md
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry/CHANGELOG.md
- packages/eslint-config-sentry/package.json
- packages/eslint-plugin-sentry/CHANGELOG.md
- packages/eslint-plugin-sentry/package.json
To help people migrate from `grid-emotion`
> feat(docs): Add link to `grid-emotion` migration guide

- CHANGELOG.md
- lerna.json
- packages/eslint-config-sentry-app/CHANGELOG.md
- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-react/CHANGELOG.md
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry/package.json
- packages/eslint-plugin-sentry/package.json
Direct imports of `marked` are restricted so that we can ensure sanitation
of `marked` output (i.e. for XSS)
> feat(rule): Restrict import of `marked`

- CHANGELOG.md
- lerna.json
- packages/eslint-config-sentry-app/CHANGELOG.md
- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
Instead, import the specific module. e.g. `import isEqual from 'lodash/isEqual'`
> feat(rule): Forbid importing directly from main  module

- packages/eslint-config-sentry-app/strict.js
`grid-emotion` has been deprecated for quite awhile, and reflexbox is the updated and maintained version of it.
We updated the library while upgrading `emotion` here: https://github.com/getsentry/sentry/pull/15106
> feat(rule): Update `grid-emotion` rule to new library: `reflexbox`

- packages/eslint-config-sentry-react/rules/imports.js
**Type:** Refactor 
**Description:**
As discussed at the TSC meeting, I activated the `'import/order'` eslint rule in this PR, so that our imports can be clearer.
The order is as shown in the following example:
```js
// 1. node "builtin" modules
import fs from 'fs';
import path from 'path';
// 2. "external" modules
import _ from 'lodash';
import chalk from 'chalk';
// 3. "internal" modules
// (if you have configured your path or webpack to handle your internal paths differently)
import foo from 'src/foo';
// 4. modules from a "parent" directory
import foo from '../foo';
import qux from '../../foo/qux';
// 5. "sibling" modules from the same or a sibling's directory
import bar from './bar';
import baz from './bar/baz';
// 6. "index" of the current directory
import main from './';
```
I've …
> refactor(style): activate eslint import/order

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/strict.js
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-config-sentry-react/rules/react.js
Currently, the typescript parser and plugins are defined in our
application, move to this configuration
> feat(rule): Move typescript eslint parser and plugin into app config

- lerna.json
- packages/eslint-config-sentry-app/index.js
This will group imports starting with these prefixes in separate groups
> feat(rule): Group `sentry`, `getsentry`, and `admin` separately

- packages/eslint-config-sentry-react/rules/imports.js
This makes it required that any dynamic import must be prefixed with `webpackChunkName`. See https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/dynamic-import-chunkname.md
> feat(rule): Dynamic imports require `webpackChunkName`

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/strict.js
This moves the rule from "strict" to "relaxed" (default).
> feat(rule): Promote `@typescript-eslint/no-unused-vars` to default ruleset

- packages/eslint-config-sentry-app/index.js
We should now only be using `@sentry/react`.
> feat(rule): Add rule restricting usage of @sentry/browser

- .github/workflows/integration.yml
- lerna.json
- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
- packages/eslint-plugin-sentry/docs/rules/no-to-match-snapshot.md
- packages/eslint-plugin-sentry/lib/rules/no-to-match-snapshot.js
- packages/eslint-plugin-sentry/package.json
- packages/eslint-plugin-sentry/tests/lib/rules/no-to-match-snapshot.js
This disallows use of `toMatchSnapshot()`, opting for visual snapshots instead. This is `fixable`.
> feat(rule): Add plugin to disallow use of `toMatchSnapshot()`

- packages/eslint-config-sentry-app/index.js
This makes `sentry-locale` and `sentry-images` a separate group from `sentry` (`app`), as well as `getsentry-images` being its own group.
> feat(rule): Change import sort groups for `(get)sentry-images`

- packages/eslint-config-sentry-react/rules/react.js
We'll be switching to the new JSX transform for getsentry/sentry and these rules are no longer required.
Breakout from getsentry/sentry#25796
> feat: Relax the JSX transform rules.

- packages/eslint-config-sentry-react/index.js
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
Adding the https://github.com/testing-library/eslint-plugin-testing-library
It will help us to follow best practices and anticipate common mistakes when writing tests with Testing Library.
> feat: Add eslint-plugin-testing-library

- packages/eslint-config-sentry-react/index.js
As soon as we merge the PR https://github.com/getsentry/sentry/pull/29948 I believe this rule can be turned on
> ref(custom-rule): Remove testing-library/prefer-screen-queries rule

- packages/eslint-config-sentry-app/index.js
Prettier was overriding this rule, as discovered here https://github.com/getsentry/sentry/pull/30878#discussion_r778209923
> ref: Fix curly rule due to prettier override

- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
Looking to upgrade to `@testing-library/dom` v8 in sentry which this uses
> feat: upgrade react testing library lint plugins

- packages/eslint-config-sentry-react/index.js
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
Adding the https://github.com/infctr/eslint-plugin-typescript-sort-keys
This rule is fixable and will help us keep the types sorted alphabetically while respecting the order of required vs. optional props.
No need to do this manually during code reviews anymore.
> feat: Add eslint-plugin-typescript-sort-keys

- packages/eslint-config-sentry-app/index.js
Add '@testing-library' to the restrict rule list, so we don't forget to import from `sentry-test/reactTestingLibrary`
> ref(restrict-rules): Add @testing-library to the list

- packages/eslint-config-sentry-app/index.js
Adding all @testing-library dependencies separated, since `@testing-library/*` or `@testing-library `don't seem to work 
requires https://github.com/getsentry/sentry/pull/31925
> ref(no-restricted-imports): Add explicit @testing-library names

- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-config-sentry-react/yarn.lock
This should fix the Typescript warnings we see in CI and locally when running lint.
> chore: Update estree libraries

- packages/eslint-config-sentry-react/rules/imports.js
In the land of language servers where auto-importing uses the named default exports as hints, we should probably never allow anonymous default exports.
> feat: Do not allow ANY anonymous default exports

- .github/workflows/integration.yml
The relax file is gone
See https://github.com/getsentry/sentry/pull/32989
> fix: Lint integration tests

- packages/eslint-config-sentry-app/strict.js
The sentry-test/enzyme rule never seems to have actually been applied. It was originally added in [0] but turns it the syntax wasn't right (it's actually not simple to have both warnings and errors for a single no-restricted-imports rule, see [1]).
This just removes it, thus fixing the configuration syntax.
[0]: https://github.com/getsentry/eslint-config-sentry/pull/113
[1]: https://github.com/eslint/eslint/issues/14061
> fix: Remove invalid no-restricted-imports syntax

- packages/eslint-config-sentry-react/rules/imports.js
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-anonymous-default-export.md
turns out that the default is actually
```tsx
"import/no-anonymous-default-export": ["error", {
"allowArray": false,
"allowArrowFunction": false,
"allowAnonymousClass": false,
"allowAnonymousFunction": false,
"allowCallExpression": true, // The true value here is for backward compatibility
"allowLiteral": false,
"allowObject": false
}]
```
`allowCallExpression` was allowing `export default styled()`...`;` through
> fix: Actually diasslow all unnamed default exports

- packages/eslint-config-sentry-react/index.js
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
By default, this is set to warn on missing dependencies and error on hook rules. I'll add the plugin manually and test on getsentry/sentry to prepare for this PR in case it would break master.
https://reactjs.org/docs/hooks-rules.html is a good read to understand what the plugin does, but also how hooks are meant to be called and why they cannot be conditionally called (https://reactjs.org/docs/hooks-rules.html#explanation).
> feat(eslint-react): add hook rules

- packages/eslint-config-sentry/rules/base.js
Disallows a function to be `async` unless it has an `await` inside the body
> feat: Add require-await rule

- packages/eslint-config-sentry-app/index.js
> Don’t ever use the types Number, String, Boolean, Symbol, or Object These types refer to non-primitive boxed objects that are almost never used appropriately in JavaScript code.
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html
> feat: Ban `String` `Number` `Object` as types

- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
Does not seem to work with our getsentry setup, tried a bunch of different configs. Just going to downgrade it for now.
I think its the switch to "get-tsconfig" or maybe tsconfig-paths in v3 https://github.com/import-js/eslint-import-resolver-typescript/releases/tag/v3.0.0
see: https://github.com/getsentry/getsentry/pull/8275
> fix: Downgrade import-resolver-typescript

- packages/eslint-plugin-sentry/lib/rules/t-only-literal.js
- packages/eslint-plugin-sentry/tests/lib/rules/t-only-literal.js
This should help us to no longer produce translation calls on the
frontend that can't actually be translated since they're dynamic.
See here where I fixed a bunch https://github.com/getsentry/sentry/pull/40304
I started trying to make it fixable. But there's a good number of cases
to account for to make that work, so I gave up haha.
> Add new `t-only-literal` rule for translations

- packages/eslint-config-sentry-app/index.js
I'm adding the `withSentryRouter` higher-order component in https://github.com/getsentry/sentry/pull/41797, which is a wrapper of `withRouter` from the `react-router` library. I aim to replace any and all instances of `withRouter` that wrap class components with `withSentryRouter` in both `sentry` and `getsentry`.
Since we discourage the use of `withRouter` in new React components, we should also discourage the use of `withSentryRouter` in new React components as well.
> feat: Add rule to discourage use of withSentryRouter

- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
This borks `getsentry` CI.
See https://github.com/getsentry/eslint-config-sentry/pull/158
> fix: Downgrade eslint-import-resolver-typescript

- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
Safari prior to last week does not support lookbehinds of any kind in regexp patterns and crashes should it encounter one. We've forgotten about this limitation several times and catching it with lint should help prevent future problems.
> feat: Add rule to disallow lookbehinds in regexp

- packages/eslint-config-sentry-app/index.js
disables the warning when typescript is not within the explicit version. **usually** there is not issues with using a newer version
docs - https://typescript-eslint.io/architecture/parser/#configuration
other popular libraries that disable this check https://github.com/xojs/eslint-config-xo-typescript/blob/631c7b8a8885737dad8ea34d21610fcb0331baf0/index.js#LL80C3-L80C45
> feat: Disable typescript version mismatch warning

- packages/eslint-config-sentry/rules/base.js
Enforce comments to use this style
```
// This is a comment
// that spans across multiple lines
```
You CAN NOT use:
```
/*
* This type of comment
*/
```
You CAN still use:
```
/**
* This is a jsdoc style comment. Text here will appear in the language
* server help text hover
*/
```
> Add multiline-comment-style rule

- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-docs/package.json
silences this warning
```
eslint-config-sentry-app#prettier@1.x || 2.x" doesn't satisfy found match of "prettier@3.0.3
```
> fix: Add v3 to prettier peer dependency, remove v1

- lerna.json
- packages/eslint-config-sentry-react/rules/imports.js
Upon investigation @JoshuaKGoldberg found some interesting optimizations in our Eslint rules. There is an open issue in `typescript-eslint` about Sentry's performance: https://github.com/typescript-eslint/typescript-eslint/issues/8424
These rules are not recommended to be enabled with typescript-eslint rules. Ref: https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting/#eslint-plugin-import
> perf: get rid of `eslint-plugin-import` rules

- biome.json
- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-docs/index.js
- packages/eslint-config-sentry-docs/package.json
We no longer need webpack to resolve things, typescript resolver should be used in 99% of places. This is causing getsentry to hang currently
> feat: Remove webpack resolver

- .github/workflows/integration.yml
- package.json
- packages/eslint-config-sentry-app/index.js
- packages/eslint-config-sentry-app/package.json
- packages/eslint-config-sentry-app/yarn.lock
- packages/eslint-config-sentry-react/package.json
- packages/eslint-config-sentry-react/yarn.lock
- yarn.lock
support for latest version of typescript
> deps: Upgrade various packages
